server
{
	listen 443 ssl;
	server_name himousta.42.fr;

	include /etc/nginx/mime.types;

	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_certificate /etc/ssl/certs/inception.crt;
	ssl_certificate_key /etc/ssl/private/inception.key;

	root /var/www/wordpress;
	index index.php;


	location / {
		try_files $uri $uri/ /index.php$is_args$args;
	}

	location ~ \.php$ {
		# load the default fastcgi provided by debian
		include snippets/fastcgi-php.conf;
		# Tell PHP that the connection is secure!
		fastcgi_param HTTPS on;
		# connect nginx to backend wordpress container
		fastcgi_pass wordpress:9000;
	}

	location /adminer {
		# Tell FastCGI we are targeting a PHP file
		fastcgi_index index.php;
		
		# Load the default FastCGI security and environment variables
		include /etc/nginx/fastcgi_params;
		
		# point to the absolute path INSIDE the Adminer container
		fastcgi_param SCRIPT_FILENAME /var/www/adminer/index.php;
		
		# Shoot the traffic across the Docker network to the new container
		fastcgi_pass adminer:9000;
	}
}
