server
{
### security Rules

	# subj forbids http traffic -> 443 to force this port only + expects SSL traffic (https)
	listen 443 ssl; 

	# force this domain name
	server_name localhost;
	#himousta.42.fr;

	include /etc/nginx/mime.types;

	# modern secure protocols
	ssl_protocols TLSv1.2 TLSv1.3;

	# lock and unlock traffic keys 
	ssl_certificate /etc/ssl/certs/inception.crt;
	ssl_certificate_key /etc/ssl/private/inception.key;

### delivry rules

	# path inside the container
	root /var/www/wordpress;

	# default page loaded 
	index index.php;


### traffic controllers

	location / {
		# find the exact file(uri) -> then folder(uri/) -> if it fail show 404 error
		#try_files $uri $uri/ =404;
		try_files $uri $uri/ /index.php$is_args$args;
	}

	location ~ \.php$ {
		# load the default fastcgi provided by debian
		include snippets/fastcgi-php.conf;
		# Tell PHP that the connection is secure!
        fastcgi_param HTTPS on;
		# connect nginx to backend wordpress container
		fastcgi_pass wordpress:9000;
	}

	# Intercept any URL starting with /adminer
    location /adminer {
        # Tell FastCGI we are targeting a PHP file
        fastcgi_index index.php;
        
        # Load the default FastCGI security and environment variables
        include /etc/nginx/fastcgi_params;
        
        # Explicitly point to the absolute path INSIDE the Adminer container
        fastcgi_param SCRIPT_FILENAME /var/www/adminer/index.php;
        
        # Shoot the traffic across the Docker network to the new container
        fastcgi_pass adminer:9000;
    }
}


# fastcgi_pass wordpress:9000 : It takes the trapped PHP request and passes it over port 9000
#								to the container named wordpress so PHP-FPM can translate it 
#								into HTML for the user.