server {
    # We will use port 3000 so it doesn't conflict with your main WordPress NGINX (Port 443)
    listen 3000;
    listen [::]:3000;

    server_name _;

    # The exact folder where we will place your index.html inside the container
    root /var/www/website;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}