# --- CORE DAEMON ---
# Run in foreground (keeps Docker container alive)
listen=YES

# FORCE FOREGROUND: Do not let Docker kill the container!
background=NO

# Bypass kernel sandbox to prevent Docker crash
seccomp_sandbox=NO

# --- AUTH & UPLOADS ---
# Allow our .env user to log in
local_enable=YES
# Allow uploading, deleting, and editing files
write_enable=YES
# Set correct file permissions for NGINX/PHP
local_umask=022

# --- SECURITY JAIL ---
# Trap the user so they can't access root (/)
chroot_local_user=YES
# Prevent crash when the trap folder is writable
allow_writeable_chroot=YES
# Force the login directly into the web folder
local_root=/var/www/wordpress
secure_chroot_dir=/var/run/vsftpd/empty

# --- DOCKER NETWORKING ---
# Enable passive mode for file transfers
pasv_enable=YES
# Start of exposed port range
pasv_min_port=40000
# End of exposed port range
pasv_max_port=40100
